# -*- coding: utf-8 -*-
"""My First PM Code using cheche_pm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYrSaXJUvXcmXUkMhvXroWjpYTuB_T3V

# Installation

Start with cheche_pm installation
"""

!pip install cheche_pm

import numpy as np
import pandas as pd
from cheche_pm import Project

"""Create Empty Project Instance"""

p = Project() # create empty project instance

p.add_activity(activity_name='A',activity_duration = 5, activity_precedence= [None], a_desc= 'F.House', activity_resources=[1,0,0])
p.add_activity(activity_name='B',activity_duration = 2, activity_precedence= [None], a_desc= 'F.Pool', activity_resources=[1,0,0])
p.add_activity(activity_name='C',activity_duration = 5, activity_precedence= ['A'], a_desc= 'Walls', activity_resources=[0,1,0])
p.add_activity(activity_name='D',activity_duration = 6, activity_precedence= ['B'], a_desc= 'Pool', activity_resources=[0,0,1])
p.add_activity(activity_name='E',activity_duration = 5, activity_precedence= ['C'], a_desc= 'Roof', activity_resources=[0,1,0])
p.add_activity(activity_name='F',activity_duration = 2, activity_precedence= ['C'], a_desc= 'Windows', activity_resources=[0,1,0])
p.add_activity(activity_name='G',activity_duration = 3, activity_precedence= ['C'], a_desc= 'Electricity', activity_resources=[0,0,1])
p.add_activity(activity_name='H',activity_duration = 2, activity_precedence= ['E'], a_desc= 'S.Panels', activity_resources=[0,1,0])
p.add_activity(activity_name='I',activity_duration = 4, activity_precedence= ['F'], a_desc= 'Plumbing', activity_resources=[0,1,0])
p.add_activity(activity_name='J',activity_duration = 3, activity_precedence= ['H','I'], a_desc= 'Finishings', activity_resources=[0,1,0])

"""We could have imported the activities from an Excel sheet."""

p = Project.from_excel(filename='Activities RCPSP.xlsx',
                      rcpsp_format=True,
                      n_resources= 2,
                      max_resources=[7,4])

p.plot_network_diagram(plot_type = 'nx')

p.plot_network_diagram(plot_type = 'dot')

p.create_project_dict()
out_df = pd.DataFrame(p.PROJECT).T

out_df.to_excel('project_data.xlsx')

p.CPM(verbose=False)

cpm_df=pd.DataFrame(p.cpm_schedule).T

cpm_df.to_excel("cpm_data.xlsx")

import os
print(os.getcwd())

p.get_critical_path()

p.plot_gantt_cpm(True,True)

p.plot_gantt_cpm(False,True)

PL = p.get_priority_list(priority_rule= 'GRD',verbose=False,save=True)

ssg = p.SSG(PL,max_resources=[7,4],verbose=False)

p.RCPSP_plot(ssg)

p.plot_resource_levels()



psg = p.PSG(PL,max_resources=[7,4],verbose=False)

p.RCPSP_plot(psg)

p.plot_resource_levels()

p.run_all_pl_heuristics()

w_sche = p.generate_datetime_schedule(solution = psg,start_date="2023-09-03",weekends_work=False,max_resources=[7,4],verbose=True)

p.plot_date_gantt(w_sche)

p.get_critical_chain(ssg,max_resources=[7,4])

p.RCPSP_plot(ssg,resource_id=0)

p.RCPSP_plot(ssg,resource_id=1)

!pip install nbconvert